// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package contest1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContestUmClient is the client API for ContestUm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContestUmClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type contestUmClient struct {
	cc grpc.ClientConnInterface
}

func NewContestUmClient(cc grpc.ClientConnInterface) ContestUmClient {
	return &contestUmClient{cc}
}

func (c *contestUmClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/ContestUm/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContestUmServer is the server API for ContestUm service.
// All implementations must embed UnimplementedContestUmServer
// for forward compatibility
type ContestUmServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	mustEmbedUnimplementedContestUmServer()
}

// UnimplementedContestUmServer must be embedded to have forward compatible implementations.
type UnimplementedContestUmServer struct {
}

func (UnimplementedContestUmServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedContestUmServer) mustEmbedUnimplementedContestUmServer() {}

// UnsafeContestUmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContestUmServer will
// result in compilation errors.
type UnsafeContestUmServer interface {
	mustEmbedUnimplementedContestUmServer()
}

func RegisterContestUmServer(s grpc.ServiceRegistrar, srv ContestUmServer) {
	s.RegisterService(&ContestUm_ServiceDesc, srv)
}

func _ContestUm_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContestUmServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContestUm/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContestUmServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContestUm_ServiceDesc is the grpc.ServiceDesc for ContestUm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContestUm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ContestUm",
	HandlerType: (*ContestUmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _ContestUm_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contest1.proto",
}
